version: '3.3'
services:
  db:
    image: postgres:latest
    container_name: database
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"   # delete later pls

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080


volumes:
  postgres_data:
