# Generated by Django 4.2.1 on 2023-05-08 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_service', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 8, 9, 0, 12, 154010, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
